# Generated by Django 5.0.3 on 2025-07-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_total_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
